[build]
  base = "frontend"       # <--- carpeta donde está tu package.json
  publish = "frontend/dist"  # <--- carpeta que Netlify debe publicar
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
