[build]
  base = "frontend"           # Carpeta donde está tu package.json
  publish = "dist"            # Carpeta que Netlify debe publicar
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
